<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="DESKTOP-IM0U5Q7" failures="1" tests="1" name="UserTest(failed)" time="6.188" errors="0" timestamp="2023-08-31T22:04:48 IST">
  <testcase classname="api.tests.UserTest" name="testDeleteUser" time="4.208">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.tests.UserTest.testDeleteUser(UserTest.java:104)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteUser -->
  <testcase classname="api.tests.UserTest" name="testpostUser" time="0.0">
    <ignored/>
  </testcase> <!-- testpostUser -->
  <testcase classname="api.tests.UserTest" name="testUserDetails" time="0.0">
    <ignored/>
  </testcase> <!-- testUserDetails -->
  <testcase classname="api.tests.UserTest" name="testUpdate" time="0.0">
    <ignored/>
  </testcase> <!-- testUpdate -->
</testsuite> <!-- UserTest(failed) -->
